[project]
name = "qr-code-generator"
version = "0.1.0"
description = "A QR Code Generator and Scanner using Streamlit"
dependencies = [
    "streamlit",
    "qrcode[pil]",
    "opencv-python-headless"
]
requires-python = ">=3.12"

[tool.uv]
